/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void tbOnNumOfLinesChange(GTextField source, GEvent event) { //_CODE_:tbNumOfLines:220142:
  numLines = parseInt(source.getText());
} //_CODE_:tbNumOfLines:220142:

public void tbOnNumGenerationsChange(GTextField source, GEvent event) { //_CODE_:tbNumOfGenerations:841034:
  numGenerations = parseInt(source.getText());
} //_CODE_:tbNumOfGenerations:841034:

public void lstOnLineHeavinessChange(GDropList source, GEvent event) { //_CODE_:lstLineHeaviness:704182:
  opacityLvl = parseInt(source.getSelectedText());
} //_CODE_:lstLineHeaviness:704182:

public void btnOnUploadPush(GButton source, GEvent event) { //_CODE_:btnUpload:422591:
  selectInput("Select a file to process:", "fileSelected");
} //_CODE_:btnUpload:422591:

public void btnOnCreatePush(GButton source, GEvent event) { //_CODE_:btnCreate:983292:
  
  if (uploadedImage == null)
    return;
  
  isGenerating = true;
  drawer = new LineDrawer(uploadedImage);
  drawer.setNumOfGenerations(numGenerations);
  drawer.setNumOfLines(numLines);
  
  drawer.setFindDarkestPixelAlgorithm(new FindNextDarkestPixel());
  drawer.setDarkestLineAlgorithm(new FindDarkestLine());
  drawer.setLineGenerationAlgorithm(new GenerateLine());
  drawer.setDrawLineAlgorithm(new DrawGrayscaleLine(pg, opacityLvl));
  //drawer.setDrawLineAlgorithm(new DrawColorLine(pg));
  
  pg.beginDraw();
  pg.background(255);
  drawer.generate();
  pg.endDraw();
  
} //_CODE_:btnCreate:983292:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  renderWindow = new GSketchPad(this, 0, 0, 512, 512);
  title = new GLabel(this, 512, 0, 287, 52);
  title.setText("Lineatus");
  title.setTextBold();
  title.setOpaque(false);
  tbNumOfLines = new GTextField(this, 620, 69, 160, 30, G4P.SCROLLBARS_NONE);
  tbNumOfLines.setText("1600");
  tbNumOfLines.setPromptText("Number of Lines");
  tbNumOfLines.setOpaque(true);
  tbNumOfLines.addEventHandler(this, "tbOnNumOfLinesChange");
  tbNumOfGenerations = new GTextField(this, 620, 120, 160, 30, G4P.SCROLLBARS_NONE);
  tbNumOfGenerations.setText("200");
  tbNumOfGenerations.setPromptText("Number of Generations");
  tbNumOfGenerations.setOpaque(true);
  tbNumOfGenerations.addEventHandler(this, "tbOnNumGenerationsChange");
  
  lstLineHeaviness = new GDropList(this, 620, 170, 160, 150, 8);
  lstLineHeaviness.setItems(loadStrings("list_704182"), 0);
  lstLineHeaviness.addEventHandler(this, "lstOnLineHeavinessChange"); 
  
  btnUpload = new GButton(this, 530, 340, 250, 30);
  btnUpload.setText("Upload Photo");
  btnUpload.addEventHandler(this, "btnOnUploadPush");
  btnCreate = new GButton(this, 530, 390, 250, 60);
  btnCreate.setText("Create Art");
  btnCreate.addEventHandler(this, "btnOnCreatePush");
  lblNumOfLines = new GLabel(this, 520, 70, 80, 30);
  lblNumOfLines.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblNumOfLines.setText("Number of Lines");
  lblNumOfLines.setOpaque(false);
  lblNumGenerations = new GLabel(this, 520, 120, 80, 30);
  lblNumGenerations.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblNumGenerations.setText("Number of Generations");
  lblNumGenerations.setOpaque(false);
  lblLineHeavyness = new GLabel(this, 520, 170, 80, 30);
  lblLineHeavyness.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblLineHeavyness.setText("Opacity");
  lblLineHeavyness.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GSketchPad renderWindow; 
GLabel title; 
GTextField tbNumOfLines; 
GTextField tbNumOfGenerations; 
GDropList lstLineHeaviness; 
GButton btnUpload; 
GButton btnCreate; 
GButton btnSave; 
GLabel lblNumOfLines; 
GLabel lblNumGenerations; 
GLabel lblLineHeavyness; 